version: '3.8'

services:

  nginx:
    image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - ../LCApp:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php
    volumes:
      - ../LCApp:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: LCApps
      MYSQL_USER: LCApps
      MYSQL_PASSWORD: LCApps
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ../SQL:/var/lib/mysql
